// Central language text — all pages import from here
const translations = {
  en: {
    goodMorning: 'Good Morning', goodAfternoon: 'Good Afternoon', goodEvening: 'Good Evening',
    allFeatures: 'All Features', weather: 'Weather', soil: 'Soil Analysis',
    disease: 'Disease Detection', fertilizer: 'Fertilizer', community: 'Community', market: 'Market',
    weatherDesc: 'Live AI forecasts', soilDesc: 'Nutrients & crops', diseaseDesc: 'AI image scan',
    fertilizerDesc: 'Smart dosage', communityDesc: 'Connect & learn', marketDesc: 'Live mandi prices',
    govtSchemes: 'Government Schemes', benefitsForYou: 'Benefits for You',
    testimonials: 'Testimonials', whatFarmersSay: 'What Farmers Say',
    farmingTips: 'Farming Tips', trustedBy: 'Trusted by 50,000+ Indian Farmers',
    quickScan: 'Detect Crop Disease', quickScanSub: 'AI identifies 400+ diseases • Click to scan',
    step1: 'Click photo of sick crop', step2: 'AI scans in seconds', step3: 'Get treatment plan',
    openCamera: 'Open Camera', openCameraDesc: 'Point at infected leaf or crop',
    retake: 'Retake Photo', seeFullReport: 'See Full Report & All Steps →',
    signOut: 'Sign Out', change: 'Change', language: 'Language',
    irrigationGuide: 'Irrigation Guide', organicFarming: 'Organic Farming',
    tip1: '💡 Rabi season — ideal time to prepare soil for wheat sowing',
    tip2: '🌧️ High humidity — watch for fungal disease on leaves this week',
    tip3: '📈 Onion prices rising in APMC — consider selling in 7 days',
    tip4: '💧 Reduce irrigation 20% — soil moisture is optimal today',
    tip5: '🌱 Apply organic compost now for better Rabi yields',
    todaysTip: "TODAY'S AI TIP",
    farmer: 'Farmer', login: 'Login', signup: 'Sign Up', logout: 'Logout',
    phone: 'Phone Number', password: 'Password', name: 'Full Name', location: 'Location',
    analyzeBtn: 'Analyze', detectBtn: 'Detect Disease', submitBtn: 'Submit',
    cancelBtn: 'Cancel', searchPlaceholder: 'Search...', noData: 'No data available',
    loading: 'Loading...', success: 'Success', error: 'Something went wrong',
    howToUse: 'HOW TO USE', followSteps: 'FOLLOW THESE STEPS',
    commonDiseases: 'Common Diseases', commonFertilizers: 'Common Types',
    soilGuide: 'Soil Guide', seasonCrops: 'Season Crops', analysis: 'Analysis',
    shareWithFarmers: 'Share with farmers...', createPost: 'Create Post',
    postTitle: 'Post title (required)', postContent: 'Share your experience...',
    addPhotoVideo: 'Add Photo or Video', photo: 'Photo', video: 'Video/Reel', camera: 'Camera',
    sendComment: 'Send', writeComment: 'Write a comment...', readMore: 'Read more ▼',
    showLess: 'Show less ▲', justNow: 'just now', livePrice: 'Live Prices',
    compare: 'Compare', bestTime: 'Best Time', perQuintal: 'per quintal',
    allStates: 'All States', searchMarket: 'Search crop or market...',
    bestSellTime: 'BEST TIME TO SELL', updatedAt: 'Updated',
    welcomeBack: 'Welcome Back', loginAccount: 'Login to your farmer account',
    createAccount: 'Create Free Account', joinAgrismart: 'Join AgriSmart',
    alreadyRegistered: 'Already registered?', newFarmer: 'New farmer?',
    fieldDetails: 'YOUR FIELD DETAILS', cropType: 'Crop Type', fieldSize: 'Field Size (acres)',
    soilType: 'Soil Type', aiAnalyze: 'Get AI Soil Report', soilNutrients: 'SOIL NUTRIENTS',
    selectSoilType: 'SELECT SOIL TYPE', currentSeason: 'CURRENT SEASON',
    findBestCrops: 'Find Best Crops', captureFertilizer: 'CAPTURE FERTILIZER BAG',
    takePhoto: 'Take Photo', takePhotoDesc: 'Point camera at fertilizer bag label',
    orGallery: 'Or choose from gallery', analyzeBtn2: 'Analyze Fertilizer with AI',
    scanAnother: 'Scan Another Fertilizer', retakePhoto: 'Retake Photo',
    firstAction: 'First action', seeFullReportDisease: 'See Full Report →',
    aiAnalyzing: 'AI Analyzing...', analyzing: 'AI Analyzing Crop...',
    diseaseDetected: 'Disease detected — act now', healthyCrop: 'Your crop is healthy!',
    treatmentPlan: 'Treatment Plan — Follow in Order', prevention: 'Prevention for Next Season',
    symptomsObserved: 'Symptoms Observed', confidence: 'AI Confidence',
    analyzeAnother: 'Analyze Another Crop', howToDetect: 'HOW TO DETECT',
    selectLanguage: 'Choose Language', continueIn: 'Continue in',
    languageNote: 'You can change this anytime in settings',
    applyNow: 'Apply now →', tapToApply: 'Tap to apply →',
  },
  hi: {
    goodMorning: 'सुप्रभात', goodAfternoon: 'नमस्कार', goodEvening: 'शुभ संध्या',
    allFeatures: 'सभी सुविधाएं', weather: 'मौसम', soil: 'मिट्टी विश्लेषण',
    disease: 'रोग पहचान', fertilizer: 'उर्वरक सलाहकार', community: 'समुदाय', market: 'बाज़ार',
    weatherDesc: 'AI मौसम पूर्वानुमान', soilDesc: 'पोषक तत्व और फसलें', diseaseDesc: 'AI छवि स्कैन',
    fertilizerDesc: 'स्मार्ट खुराक', communityDesc: 'जुड़ें और सीखें', marketDesc: 'लाइव मंडी भाव',
    govtSchemes: 'सरकारी योजनाएं', benefitsForYou: 'आपके लिए लाभ',
    testimonials: 'प्रशंसापत्र', whatFarmersSay: 'किसान क्या कहते हैं',
    farmingTips: 'खेती के टिप्स', trustedBy: '50,000+ भारतीय किसानों का भरोसा',
    quickScan: 'फसल रोग पहचानें', quickScanSub: 'AI 400+ रोग पहचानता है • स्कैन करें',
    step1: 'बीमार फसल की फोटो लें', step2: 'AI कुछ सेकंड में स्कैन करेगा', step3: 'उपचार योजना पाएं',
    openCamera: 'कैमरा खोलें', openCameraDesc: 'संक्रमित पत्ते या फसल पर कैमरा लगाएं',
    retake: 'फिर से फोटो लें', seeFullReport: 'पूरी रिपोर्ट देखें →',
    signOut: 'साइन आउट', change: 'बदलें', language: 'भाषा',
    irrigationGuide: 'सिंचाई गाइड', organicFarming: 'जैविक खेती',
    tip1: '💡 रबी सीजन — गेहूं बोने के लिए मिट्टी तैयार करने का सही समय',
    tip2: '🌧️ उच्च नमी — इस सप्ताह पत्तियों पर फफूंद रोग देखें',
    tip3: '📈 APMC में प्याज महंगा — 7 दिनों में बेचने पर विचार करें',
    tip4: '💧 सिंचाई 20% कम करें — मिट्टी की नमी आज अनुकूल है',
    tip5: '🌱 बेहतर रबी फसल के लिए अभी जैविक खाद डालें',
    todaysTip: 'आज की AI सलाह',
    farmer: 'किसान', login: 'लॉगिन', signup: 'साइन अप', logout: 'लॉगआउट',
    phone: 'फोन नंबर', password: 'पासवर्ड', name: 'पूरा नाम', location: 'स्थान',
    analyzeBtn: 'विश्लेषण करें', detectBtn: 'रोग पहचानें', submitBtn: 'जमा करें',
    cancelBtn: 'रद्द करें', searchPlaceholder: 'खोजें...', noData: 'कोई डेटा नहीं',
    loading: 'लोड हो रहा है...', success: 'सफलता', error: 'कुछ गलत हुआ',
    howToUse: 'उपयोग कैसे करें', followSteps: 'इन चरणों का पालन करें',
    commonDiseases: 'सामान्य रोग', commonFertilizers: 'सामान्य प्रकार',
    soilGuide: 'मिट्टी गाइड', seasonCrops: 'मौसमी फसलें', analysis: 'विश्लेषण',
    shareWithFarmers: 'किसानों के साथ साझा करें...', createPost: 'पोस्ट बनाएं',
    postTitle: 'पोस्ट का शीर्षक (आवश्यक)', postContent: 'अपना अनुभव साझा करें...',
    addPhotoVideo: 'फोटो या वीडियो जोड़ें', photo: 'फोटो', video: 'वीडियो/रील', camera: 'कैमरा',
    sendComment: 'भेजें', writeComment: 'टिप्पणी लिखें...', readMore: 'और पढ़ें ▼',
    showLess: 'कम दिखाएं ▲', justNow: 'अभी', livePrice: 'लाइव भाव',
    compare: 'तुलना', bestTime: 'सर्वोत्तम समय', perQuintal: 'प्रति क्विंटल',
    allStates: 'सभी राज्य', searchMarket: 'फसल या बाज़ार खोजें...',
    bestSellTime: 'बेचने का सर्वोत्तम समय', updatedAt: 'अपडेट किया',
    welcomeBack: 'वापस स्वागत है', loginAccount: 'किसान खाते में लॉगिन करें',
    createAccount: 'मुफ्त खाता बनाएं', joinAgrismart: 'AgriSmart से जुड़ें',
    alreadyRegistered: 'पहले से पंजीकृत हैं?', newFarmer: 'नए किसान?',
    fieldDetails: 'आपके खेत की जानकारी', cropType: 'फसल प्रकार', fieldSize: 'खेत का आकार (एकड़)',
    soilType: 'मिट्टी का प्रकार', aiAnalyze: 'AI मिट्टी रिपोर्ट पाएं', soilNutrients: 'मिट्टी के पोषक तत्व',
    selectSoilType: 'मिट्टी का प्रकार चुनें', currentSeason: 'वर्तमान मौसम',
    findBestCrops: 'सर्वोत्तम फसलें खोजें', captureFertilizer: 'उर्वरक बैग की फोटो लें',
    takePhoto: 'फोटो लें', takePhotoDesc: 'उर्वरक बैग के लेबल पर कैमरा लगाएं',
    orGallery: 'या गैलरी से चुनें', analyzeBtn2: 'AI से उर्वरक विश्लेषण करें',
    scanAnother: 'दूसरा उर्वरक स्कैन करें', retakePhoto: 'फिर से फोटो लें',
    firstAction: 'पहला कदम', seeFullReportDisease: 'पूरी रिपोर्ट देखें →',
    aiAnalyzing: 'AI विश्लेषण कर रहा है...', analyzing: 'AI फसल का विश्लेषण कर रहा है...',
    diseaseDetected: 'रोग मिला — तुरंत कार्रवाई करें', healthyCrop: 'आपकी फसल स्वस्थ है!',
    treatmentPlan: 'उपचार योजना — क्रम में पालन करें', prevention: 'अगले सीजन के लिए बचाव',
    symptomsObserved: 'देखे गए लक्षण', confidence: 'AI विश्वसनीयता',
    analyzeAnother: 'दूसरी फसल का विश्लेषण करें', howToDetect: 'पहचान कैसे करें',
    selectLanguage: 'भाषा चुनें', continueIn: 'जारी रखें',
    languageNote: 'आप इसे सेटिंग में कभी भी बदल सकते हैं',
    applyNow: 'अभी आवेदन करें →', tapToApply: 'आवेदन करें →',
  },
  mr: {
    goodMorning: 'सुप्रभात', goodAfternoon: 'नमस्कार', goodEvening: 'शुभ संध्याकाळ',
    allFeatures: 'सर्व वैशिष्ट्ये', weather: 'हवामान', soil: 'माती विश्लेषण',
    disease: 'रोग ओळख', fertilizer: 'खत सल्लागार', community: 'समुदाय', market: 'बाजार',
    weatherDesc: 'AI हवामान अंदाज', soilDesc: 'पोषक आणि पिके', diseaseDesc: 'AI प्रतिमा स्कॅन',
    fertilizerDesc: 'स्मार्ट डोस', communityDesc: 'जोडा आणि शिका', marketDesc: 'थेट मंडी भाव',
    govtSchemes: 'सरकारी योजना', benefitsForYou: 'तुमच्यासाठी लाभ',
    testimonials: 'प्रशंसापत्रे', whatFarmersSay: 'शेतकरी काय म्हणतात',
    farmingTips: 'शेती टिप्स', trustedBy: '50,000+ भारतीय शेतकऱ्यांचा विश्वास',
    quickScan: 'पिकाचा रोग ओळखा', quickScanSub: 'AI 400+ रोग ओळखतो • स्कॅन करा',
    step1: 'आजारी पिकाचा फोटो काढा', step2: 'AI काही सेकंदात स्कॅन करेल', step3: 'उपचार योजना मिळवा',
    openCamera: 'कॅमेरा उघडा', openCameraDesc: 'संक्रमित पान किंवा पिकावर कॅमेरा धरा',
    retake: 'पुन्हा फोटो काढा', seeFullReport: 'संपूर्ण अहवाल पहा →',
    signOut: 'साइन आउट', change: 'बदला', language: 'भाषा',
    irrigationGuide: 'सिंचन मार्गदर्शन', organicFarming: 'सेंद्रिय शेती',
    tip1: '💡 रब्बी हंगाम — गहू पेरणीसाठी माती तयार करण्याची वेळ',
    tip2: '🌧️ उच्च आर्द्रता — या आठवड्यात पानांवर बुरशी रोग पहा',
    tip3: '📈 APMC मध्ये कांदा महाग — 7 दिवसात विकण्याचा विचार करा',
    tip4: '💧 सिंचन 20% कमी करा — आज मातीतील ओलावा योग्य आहे',
    tip5: '🌱 चांगल्या रब्बी पिकासाठी आता सेंद्रिय खत टाका',
    todaysTip: 'आजचा AI सल्ला',
    farmer: 'शेतकरी', login: 'लॉगिन', signup: 'नोंदणी', logout: 'लॉगआउट',
    phone: 'फोन नंबर', password: 'पासवर्ड', name: 'पूर्ण नाव', location: 'स्थान',
    analyzeBtn: 'विश्लेषण करा', detectBtn: 'रोग ओळखा', submitBtn: 'सबमिट करा',
    cancelBtn: 'रद्द करा', searchPlaceholder: 'शोधा...', noData: 'डेटा नाही',
    loading: 'लोड होत आहे...', success: 'यशस्वी', error: 'काहीतरी चुकले',
    howToUse: 'कसे वापरावे', followSteps: 'हे चरण पाळा',
    commonDiseases: 'सामान्य रोग', commonFertilizers: 'सामान्य प्रकार',
    soilGuide: 'माती मार्गदर्शन', seasonCrops: 'हंगामी पिके', analysis: 'विश्लेषण',
    shareWithFarmers: 'शेतकऱ्यांसोबत शेअर करा...', createPost: 'पोस्ट तयार करा',
    postTitle: 'पोस्टचे शीर्षक (आवश्यक)', postContent: 'तुमचा अनुभव शेअर करा...',
    addPhotoVideo: 'फोटो किंवा व्हिडिओ जोडा', photo: 'फोटो', video: 'व्हिडिओ/रील', camera: 'कॅमेरा',
    sendComment: 'पाठवा', writeComment: 'टिप्पणी लिहा...', readMore: 'अधिक वाचा ▼',
    showLess: 'कमी दाखवा ▲', justNow: 'आत्ता', livePrice: 'थेट भाव',
    compare: 'तुलना', bestTime: 'सर्वोत्तम वेळ', perQuintal: 'प्रति क्विंटल',
    allStates: 'सर्व राज्ये', searchMarket: 'पीक किंवा बाजार शोधा...',
    bestSellTime: 'विक्रीचा सर्वोत्तम वेळ', updatedAt: 'अद्यतनित',
    welcomeBack: 'परत स्वागत आहे', loginAccount: 'शेतकरी खात्यात लॉगिन करा',
    createAccount: 'मोफत खाते तयार करा', joinAgrismart: 'AgriSmart मध्ये सामील व्हा',
    alreadyRegistered: 'आधीच नोंदणी केली?', newFarmer: 'नवीन शेतकरी?',
    fieldDetails: 'तुमच्या शेताची माहिती', cropType: 'पिकाचा प्रकार', fieldSize: 'शेताचा आकार (एकर)',
    soilType: 'मातीचा प्रकार', aiAnalyze: 'AI माती अहवाल मिळवा', soilNutrients: 'मातीचे पोषक',
    selectSoilType: 'मातीचा प्रकार निवडा', currentSeason: 'सध्याचा हंगाम',
    findBestCrops: 'सर्वोत्तम पिके शोधा', captureFertilizer: 'खत बॅगचा फोटो काढा',
    takePhoto: 'फोटो काढा', takePhotoDesc: 'खत बॅगच्या लेबलवर कॅमेरा धरा',
    orGallery: 'किंवा गॅलरीतून निवडा', analyzeBtn2: 'AI ने खत विश्लेषण करा',
    scanAnother: 'दुसरे खत स्कॅन करा', retakePhoto: 'पुन्हा फोटो काढा',
    firstAction: 'पहिली कृती', seeFullReportDisease: 'संपूर्ण अहवाल पहा →',
    aiAnalyzing: 'AI विश्लेषण करत आहे...', analyzing: 'AI पीक तपासत आहे...',
    diseaseDetected: 'रोग आढळला — आत्ता कृती करा', healthyCrop: 'तुमचे पीक निरोगी आहे!',
    treatmentPlan: 'उपचार योजना — क्रमाने पाळा', prevention: 'पुढील हंगामासाठी प्रतिबंध',
    symptomsObserved: 'दिसलेली लक्षणे', confidence: 'AI विश्वासार्हता',
    analyzeAnother: 'दुसऱ्या पिकाचे विश्लेषण करा', howToDetect: 'कसे ओळखावे',
    selectLanguage: 'भाषा निवडा', continueIn: 'पुढे जा',
    languageNote: 'तुम्ही हे सेटिंग्जमध्ये कधीही बदलू शकता',
    applyNow: 'आत्ता अर्ज करा →', tapToApply: 'अर्ज करा →',
  },
  kn: {
    goodMorning: 'ಶುಭ ಬೆಳಗು', goodAfternoon: 'ಶುಭ ಮಧ್ಯಾಹ್ನ', goodEvening: 'ಶುಭ ಸಂಜೆ',
    allFeatures: 'ಎಲ್ಲಾ ವೈಶಿಷ್ಟ್ಯಗಳು', weather: 'ಹವಾಮಾನ', soil: 'ಮಣ್ಣು ವಿಶ್ಲೇಷಣೆ',
    disease: 'ರೋಗ ಪತ್ತೆ', fertilizer: 'ಗೊಬ್ಬರ ಸಲಹೆ', community: 'ಸಮುದಾಯ', market: 'ಮಾರುಕಟ್ಟೆ',
    weatherDesc: 'AI ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ', soilDesc: 'ಪೋಷಕಾಂಶ ಮತ್ತು ಬೆಳೆ', diseaseDesc: 'AI ಚಿತ್ರ ಸ್ಕ್ಯಾನ್',
    fertilizerDesc: 'ಸ್ಮಾರ್ಟ್ ಡೋಸ್', communityDesc: 'ಸಂಪರ್ಕ ಮತ್ತು ಕಲಿ', marketDesc: 'ನೇರ ಮಂಡಿ ಬೆಲೆ',
    govtSchemes: 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು', benefitsForYou: 'ನಿಮಗೆ ಲಾಭಗಳು',
    testimonials: 'ಪ್ರಶಂಸಾಪತ್ರಗಳು', whatFarmersSay: 'ರೈತರು ಏನು ಹೇಳುತ್ತಾರೆ',
    farmingTips: 'ಕೃಷಿ ಸಲಹೆಗಳು', trustedBy: '50,000+ ಭಾರತೀಯ ರೈತರ ವಿಶ್ವಾಸ',
    quickScan: 'ಬೆಳೆ ರೋಗ ಪತ್ತೆ', quickScanSub: 'AI 400+ ರೋಗ ಪತ್ತೆ ಮಾಡುತ್ತದೆ',
    step1: 'ರೋಗಗ್ರಸ್ತ ಬೆಳೆಯ ಫೋಟೋ ತೆಗೆಯಿರಿ', step2: 'AI ಕೆಲವು ಸೆಕೆಂಡ್‌ನಲ್ಲಿ ಸ್ಕ್ಯಾನ್ ಮಾಡುತ್ತದೆ', step3: 'ಚಿಕಿತ್ಸಾ ಯೋಜನೆ ಪಡೆಯಿರಿ',
    openCamera: 'ಕ್ಯಾಮೆರಾ ತೆರೆಯಿರಿ', openCameraDesc: 'ಸೋಂಕಿತ ಎಲೆ ಅಥವಾ ಬೆಳೆಯ ಮೇಲೆ ಗುರಿ ಇಡಿ',
    retake: 'ಮತ್ತೆ ಫೋಟೋ ತೆಗೆಯಿರಿ', seeFullReport: 'ಪೂರ್ಣ ವರದಿ ನೋಡಿ →',
    signOut: 'ಸೈನ್ ಔಟ್', change: 'ಬದಲಾಯಿಸಿ', language: 'ಭಾಷೆ',
    irrigationGuide: 'ನೀರಾವರಿ ಮಾರ್ಗದರ್ಶಿ', organicFarming: 'ಸಾವಯವ ಕೃಷಿ',
    tip1: '💡 ರಬಿ ಋತು — ಗೋಧಿ ಬಿತ್ತನೆಗೆ ಮಣ್ಣು ತಯಾರಿಸಲು ಸರಿಯಾದ ಸಮಯ',
    tip2: '🌧️ ಹೆಚ್ಚಿನ ತೇವಾಂಶ — ಈ ವಾರ ಎಲೆಗಳ ಮೇಲೆ ಶಿಲೀಂಧ್ರ ರೋಗ ನೋಡಿ',
    tip3: '📈 APMC ನಲ್ಲಿ ಈರುಳ್ಳಿ ಬೆಲೆ ಏರಿದೆ — 7 ದಿನಗಳಲ್ಲಿ ಮಾರಾಟ ಮಾಡಿ',
    tip4: '💧 ನೀರಾವರಿ 20% ಕಡಿಮೆ ಮಾಡಿ — ಮಣ್ಣಿನ ತೇವಾಂಶ ಇಂದು ಸೂಕ್ತ',
    tip5: '🌱 ಉತ್ತಮ ರಬಿ ಬೆಳೆಗಾಗಿ ಈಗ ಸಾವಯವ ಗೊಬ್ಬರ ಹಾಕಿ',
    todaysTip: 'ಇಂದಿನ AI ಸಲಹೆ',
    farmer: 'ರೈತ', login: 'ಲಾಗಿನ್', signup: 'ಸೈನ್ ಅಪ್', logout: 'ಲಾಗೌಟ್',
    phone: 'ಫೋನ್ ನಂಬರ್', password: 'ಪಾಸ್ವರ್ಡ್', name: 'ಪೂರ್ಣ ಹೆಸರು', location: 'ಸ್ಥಳ',
    analyzeBtn: 'ವಿಶ್ಲೇಷಿಸಿ', detectBtn: 'ರೋಗ ಪತ್ತೆ ಮಾಡಿ', submitBtn: 'ಸಲ್ಲಿಸಿ',
    cancelBtn: 'ರದ್ದು ಮಾಡಿ', searchPlaceholder: 'ಹುಡುಕಿ...', noData: 'ಡೇಟಾ ಇಲ್ಲ',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...', success: 'ಯಶಸ್ವಿ', error: 'ಏನೋ ತಪ್ಪಾಯಿತು',
    howToUse: 'ಹೇಗೆ ಬಳಸಬೇಕು', followSteps: 'ಈ ಹಂತಗಳನ್ನು ಅನುಸರಿಸಿ',
    commonDiseases: 'ಸಾಮಾನ್ಯ ರೋಗಗಳು', commonFertilizers: 'ಸಾಮಾನ್ಯ ವಿಧಗಳು',
    soilGuide: 'ಮಣ್ಣು ಮಾರ್ಗದರ್ಶಿ', seasonCrops: 'ಋತುಮಾನ ಬೆಳೆಗಳು', analysis: 'ವಿಶ್ಲೇಷಣೆ',
    shareWithFarmers: 'ರೈತರೊಂದಿಗೆ ಹಂಚಿಕೊಳ್ಳಿ...', createPost: 'ಪೋಸ್ಟ್ ರಚಿಸಿ',
    postTitle: 'ಪೋಸ್ಟ್ ಶೀರ್ಷಿಕೆ (ಅಗತ್ಯ)', postContent: 'ನಿಮ್ಮ ಅನುಭವ ಹಂಚಿಕೊಳ್ಳಿ...',
    addPhotoVideo: 'ಫೋಟೋ ಅಥವಾ ವೀಡಿಯೊ ಸೇರಿಸಿ', photo: 'ಫೋಟೋ', video: 'ವೀಡಿಯೊ/ರೀಲ್', camera: 'ಕ್ಯಾಮೆರಾ',
    sendComment: 'ಕಳುಹಿಸಿ', writeComment: 'ಕಾಮೆಂಟ್ ಬರೆಯಿರಿ...', readMore: 'ಹೆಚ್ಚು ಓದಿ ▼',
    showLess: 'ಕಡಿಮೆ ತೋರಿಸಿ ▲', justNow: 'ಈಗಷ್ಟೇ', livePrice: 'ನೇರ ಬೆಲೆ',
    compare: 'ಹೋಲಿಕೆ', bestTime: 'ಉತ್ತಮ ಸಮಯ', perQuintal: 'ಪ್ರತಿ ಕ್ವಿಂಟಲ್',
    allStates: 'ಎಲ್ಲಾ ರಾಜ್ಯಗಳು', searchMarket: 'ಬೆಳೆ ಅಥವಾ ಮಾರುಕಟ್ಟೆ ಹುಡುಕಿ...',
    bestSellTime: 'ಮಾರಾಟದ ಉತ್ತಮ ಸಮಯ', updatedAt: 'ನವೀಕರಿಸಲಾಗಿದೆ',
    welcomeBack: 'ಮರಳಿ ಸ್ವಾಗತ', loginAccount: 'ರೈತ ಖಾತೆಗೆ ಲಾಗಿನ್ ಮಾಡಿ',
    createAccount: 'ಉಚಿತ ಖಾತೆ ರಚಿಸಿ', joinAgrismart: 'AgriSmart ಸೇರಿ',
    alreadyRegistered: 'ಈಗಾಗಲೇ ನೋಂದಾಯಿಸಿದ್ದೀರಾ?', newFarmer: 'ಹೊಸ ರೈತ?',
    fieldDetails: 'ನಿಮ್ಮ ಹೊಲದ ವಿವರ', cropType: 'ಬೆಳೆ ವಿಧ', fieldSize: 'ಹೊಲದ ಗಾತ್ರ (ಎಕರೆ)',
    soilType: 'ಮಣ್ಣಿನ ವಿಧ', aiAnalyze: 'AI ಮಣ್ಣು ವರದಿ ಪಡೆಯಿರಿ', soilNutrients: 'ಮಣ್ಣಿನ ಪೋಷಕಾಂಶಗಳು',
    selectSoilType: 'ಮಣ್ಣಿನ ವಿಧ ಆಯ್ಕೆ ಮಾಡಿ', currentSeason: 'ಪ್ರಸ್ತುತ ಋತು',
    findBestCrops: 'ಉತ್ತಮ ಬೆಳೆಗಳನ್ನು ಹುಡುಕಿ', captureFertilizer: 'ಗೊಬ್ಬರ ಚೀಲದ ಫೋಟೋ ತೆಗೆಯಿರಿ',
    takePhoto: 'ಫೋಟೋ ತೆಗೆಯಿರಿ', takePhotoDesc: 'ಗೊಬ್ಬರ ಚೀಲದ ಲೇಬಲ್ ಮೇಲೆ ಕ್ಯಾಮೆರಾ ಇಡಿ',
    orGallery: 'ಅಥವಾ ಗ್ಯಾಲರಿಯಿಂದ ಆಯ್ಕೆ ಮಾಡಿ', analyzeBtn2: 'AI ನಿಂದ ಗೊಬ್ಬರ ವಿಶ್ಲೇಷಿಸಿ',
    scanAnother: 'ಮತ್ತೊಂದು ಗೊಬ್ಬರ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ', retakePhoto: 'ಮತ್ತೆ ಫೋಟೋ ತೆಗೆಯಿರಿ',
    firstAction: 'ಮೊದಲ ಕ್ರಮ', seeFullReportDisease: 'ಪೂರ್ಣ ವರದಿ ನೋಡಿ →',
    aiAnalyzing: 'AI ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...', analyzing: 'AI ಬೆಳೆ ಪರೀಕ್ಷಿಸುತ್ತಿದೆ...',
    diseaseDetected: 'ರೋಗ ಕಂಡುಬಂದಿದೆ — ತಕ್ಷಣ ಕ್ರಮ ತೆಗೆಯಿರಿ', healthyCrop: 'ನಿಮ್ಮ ಬೆಳೆ ಆರೋಗ್ಯಕರವಾಗಿದೆ!',
    treatmentPlan: 'ಚಿಕಿತ್ಸಾ ಯೋಜನೆ — ಕ್ರಮದಲ್ಲಿ ಅನುಸರಿಸಿ', prevention: 'ಮುಂದಿನ ಋತುವಿಗೆ ತಡೆಗಟ್ಟುವಿಕೆ',
    symptomsObserved: 'ಕಂಡ ಲಕ್ಷಣಗಳು', confidence: 'AI ವಿಶ್ವಾಸ',
    analyzeAnother: 'ಮತ್ತೊಂದು ಬೆಳೆ ವಿಶ್ಲೇಷಿಸಿ', howToDetect: 'ಹೇಗೆ ಪತ್ತೆ ಮಾಡಬೇಕು',
    selectLanguage: 'ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ', continueIn: 'ಮುಂದುವರಿಯಿರಿ',
    languageNote: 'ನೀವು ಇದನ್ನು ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ಯಾವಾಗಲಾದರೂ ಬದಲಾಯಿಸಬಹುದು',
    applyNow: 'ಈಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ →', tapToApply: 'ಅರ್ಜಿ ಸಲ್ಲಿಸಿ →',
  },
  ta: {
    goodMorning: 'காலை வணக்கம்', goodAfternoon: 'மதிய வணக்கம்', goodEvening: 'மாலை வணக்கம்',
    allFeatures: 'அனைத்து அம்சங்கள்', weather: 'வானிலை', soil: 'மண் பகுப்பாய்வு',
    disease: 'நோய் கண்டறிதல்', fertilizer: 'உர ஆலோசகர்', community: 'சமூகம்', market: 'சந்தை',
    weatherDesc: 'AI வானிலை முன்னறிவிப்பு', soilDesc: 'ஊட்டச்சத்து மற்றும் பயிர்', diseaseDesc: 'AI படம் ஸ்கேன்',
    fertilizerDesc: 'ஸ்மார்ட் அளவு', communityDesc: 'இணை மற்றும் கற்று', marketDesc: 'நேரடி மண்டி விலை',
    govtSchemes: 'அரசு திட்டங்கள்', benefitsForYou: 'உங்களுக்கான நலன்கள்',
    testimonials: 'சான்றுரைகள்', whatFarmersSay: 'விவசாயிகள் என்ன சொல்கிறார்கள்',
    farmingTips: 'விவசாய குறிப்புகள்', trustedBy: '50,000+ இந்திய விவசாயிகளின் நம்பிக்கை',
    quickScan: 'பயிர் நோய் கண்டறி', quickScanSub: 'AI 400+ நோய்களை கண்டறியும்',
    step1: 'நோயுற்ற பயிரின் புகைப்படம் எடுக்கவும்', step2: 'AI சில நொடிகளில் ஸ்கேன் செய்யும்', step3: 'சிகிச்சை திட்டம் பெறுங்கள்',
    openCamera: 'கேமராவை திறக்கவும்', openCameraDesc: 'பாதிக்கப்பட்ட இலை அல்லது பயிரை நோக்கவும்',
    retake: 'மீண்டும் புகைப்படம் எடுக்கவும்', seeFullReport: 'முழு அறிக்கை காணவும் →',
    signOut: 'வெளியேறு', change: 'மாற்று', language: 'மொழி',
    irrigationGuide: 'நீர்ப்பாசன வழிகாட்டி', organicFarming: 'இயற்கை விவசாயம்',
    tip1: '💡 ரபி பருவம் — கோதுமை விதைப்புக்கு மண் தயாரிக்க சரியான நேரம்',
    tip2: '🌧️ அதிக ஈரப்பதம் — இந்த வாரம் இலைகளில் பூஞ்சை நோய் கவனிக்கவும்',
    tip3: '📈 APMC யில் வெங்காயம் விலை ஏறியது — 7 நாட்களில் விற்கலாம்',
    tip4: '💧 நீர்ப்பாசனம் 20% குறைக்கவும் — இன்று மண் ஈரப்பதம் சரியாக உள்ளது',
    tip5: '🌱 சிறந்த ரபி பயிருக்கு இப்போது இயற்கை உரம் இடுங்கள்',
    todaysTip: 'இன்றைய AI ஆலோசனை',
    farmer: 'விவசாயி', login: 'உள்நுழை', signup: 'பதிவு செய்', logout: 'வெளியேறு',
    phone: 'தொலைபேசி எண்', password: 'கடவுச்சொல்', name: 'முழு பெயர்', location: 'இடம்',
    analyzeBtn: 'பகுப்பாய்வு செய்', detectBtn: 'நோய் கண்டறி', submitBtn: 'சமர்ப்பி',
    cancelBtn: 'ரத்து செய்', searchPlaceholder: 'தேடு...', noData: 'தரவு இல்லை',
    loading: 'ஏற்றுகிறது...', success: 'வெற்றி', error: 'ஏதோ தவறு',
    howToUse: 'எவ்வாறு பயன்படுத்துவது', followSteps: 'இந்த படிகளை பின்பற்றுங்கள்',
    commonDiseases: 'பொதுவான நோய்கள்', commonFertilizers: 'பொதுவான வகைகள்',
    soilGuide: 'மண் வழிகாட்டி', seasonCrops: 'பருவகால பயிர்கள்', analysis: 'பகுப்பாய்வு',
    shareWithFarmers: 'விவசாயிகளுடன் பகிரவும்...', createPost: 'இடுகை உருவாக்கு',
    postTitle: 'இடுகை தலைப்பு (தேவை)', postContent: 'உங்கள் அனுபவம் பகிரவும்...',
    addPhotoVideo: 'படம் அல்லது வீடியோ சேர்க்கவும்', photo: 'படம்', video: 'வீடியோ/ரீல்', camera: 'கேமரா',
    sendComment: 'அனுப்பு', writeComment: 'கருத்து எழுதுங்கள்...', readMore: 'மேலும் படிக்க ▼',
    showLess: 'குறைவாக காட்டு ▲', justNow: 'இப்போது', livePrice: 'நேரடி விலை',
    compare: 'ஒப்பீடு', bestTime: 'சிறந்த நேரம்', perQuintal: 'ஒரு குவிண்டால்',
    allStates: 'அனைத்து மாநிலங்கள்', searchMarket: 'பயிர் அல்லது சந்தை தேடு...',
    bestSellTime: 'விற்பனைக்கு சிறந்த நேரம்', updatedAt: 'புதுப்பிக்கப்பட்டது',
    welcomeBack: 'மீண்டும் வரவேற்கிறோம்', loginAccount: 'விவசாயி கணக்கில் உள்நுழைக',
    createAccount: 'இலவச கணக்கு உருவாக்கு', joinAgrismart: 'AgriSmart ஐ சேருங்கள்',
    alreadyRegistered: 'ஏற்கனவே பதிவு செய்தீர்களா?', newFarmer: 'புதிய விவசாயியா?',
    fieldDetails: 'உங்கள் வயல் விவரங்கள்', cropType: 'பயிர் வகை', fieldSize: 'வயல் அளவு (ஏக்கர்)',
    soilType: 'மண் வகை', aiAnalyze: 'AI மண் அறிக்கை பெறுங்கள்', soilNutrients: 'மண் ஊட்டச்சத்துக்கள்',
    selectSoilType: 'மண் வகை தேர்ந்தெடுக்கவும்', currentSeason: 'தற்போதைய பருவம்',
    findBestCrops: 'சிறந்த பயிர்களை கண்டறி', captureFertilizer: 'உர பை புகைப்படம் எடுக்கவும்',
    takePhoto: 'புகைப்படம் எடுக்கவும்', takePhotoDesc: 'உர பையின் லேபிளை கேமராவில் பதிவு செய்யுங்கள்',
    orGallery: 'அல்லது கேலரியிலிருந்து தேர்ந்தெடுக்கவும்', analyzeBtn2: 'AI மூலம் உரம் பகுப்பாய்வு செய்',
    scanAnother: 'மற்றொரு உரம் ஸ்கேன் செய்யவும்', retakePhoto: 'மீண்டும் புகைப்படம் எடுக்கவும்',
    firstAction: 'முதல் நடவடிக்கை', seeFullReportDisease: 'முழு அறிக்கை காணவும் →',
    aiAnalyzing: 'AI பகுப்பாய்வு செய்கிறது...', analyzing: 'AI பயிரை பரிசோதிக்கிறது...',
    diseaseDetected: 'நோய் கண்டறியப்பட்டது — இப்போதே நடவடிக்கை எடுங்கள்', healthyCrop: 'உங்கள் பயிர் ஆரோக்கியமாக உள்ளது!',
    treatmentPlan: 'சிகிச்சை திட்டம் — வரிசையில் பின்பற்றுங்கள்', prevention: 'அடுத்த பருவத்திற்கு தடுப்பு',
    symptomsObserved: 'கண்டறியப்பட்ட அறிகுறிகள்', confidence: 'AI நம்பகத்தன்மை',
    analyzeAnother: 'மற்றொரு பயிரை பகுப்பாய்வு செய்', howToDetect: 'எவ்வாறு கண்டறிவது',
    selectLanguage: 'மொழி தேர்ந்தெடுக்கவும்', continueIn: 'தொடரவும்',
    languageNote: 'நீங்கள் இதை எப்போது வேண்டுமானாலும் அமைப்புகளில் மாற்றலாம்',
    applyNow: 'இப்போது விண்ணப்பிக்கவும் →', tapToApply: 'விண்ணப்பிக்கவும் →',
  },
}

export const getLang = () => localStorage.getItem('lang') || 'en'
export const T = (key) => {
  const lang = getLang()
  return translations[lang]?.[key] || translations['en']?.[key] || key
}
export default translations
